// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BpmnApp.DataAccess.Ef.Models
{
    public partial class AppUser
    {
        public AppUser()
        {
            Diagram = new HashSet<Diagram>();
            SubProcessDiagram = new HashSet<SubProcessDiagram>();
            UserDiagram = new HashSet<UserDiagram>();
        }

        public Guid UserId { get; set; }
        public string UserNme { get; set; }
        public string UserLoginName { get; set; }
        public string Password { get; set; }

        public virtual ICollection<Diagram> Diagram { get; set; }
        public virtual ICollection<SubProcessDiagram> SubProcessDiagram { get; set; }
        public virtual ICollection<UserDiagram> UserDiagram { get; set; }
    }
}