// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BpmnApp.DataAccess.Ef.Models
{
    public partial class Diagram
    {
        public Diagram()
        {
            SubProcessDiagram = new HashSet<SubProcessDiagram>();
            UserDiagram = new HashSet<UserDiagram>();
        }

        public Guid DiagramId { get; set; }
        public Guid UserCreatorId { get; set; }
        public DateTime CreatedDate { get; set; }
        public string DiagramProcessName { get; set; }
        public string DiagramXml { get; set; }

        public virtual AppUser UserCreator { get; set; }
        public virtual ICollection<SubProcessDiagram> SubProcessDiagram { get; set; }
        public virtual ICollection<UserDiagram> UserDiagram { get; set; }
    }
}