// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BpmnApp.DataAccess.Ef.Models
{
    public partial class SubProcessDiagram
    {
        public Guid SubProcessDiagramId { get; set; }
        public Guid ParentDiagramId { get; set; }
        public string ParentElementName { get; set; }
        public Guid UserCreatorId { get; set; }
        public DateTime CreatedDate { get; set; }
        public string DiagramXml { get; set; }

        public virtual Diagram ParentDiagram { get; set; }
        public virtual AppUser UserCreator { get; set; }
    }
}